#!/usr/bin/env node
// Verifies every internal link in the built site resolves to a real page and,
// for links with a fragment, to a real heading on that page.
//
// Astro does not rewrite or validate links inside markdown content, so a typo
// or a page rename fails silently and only shows up as a 404 in production.
// Run after `astro build`.

import { readFileSync, globSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DIST = path.join(ROOT, 'dist');
const BASE = '/doc';

if (!existsSync(DIST)) {
    console.error('dist/ не найден — сначала `npm run build`.');
    process.exit(1);
}

const pages = globSync('**/*.html', { cwd: DIST });

const urlOf = (rel) => `${BASE}/${rel.replace(/index\.html$/, '').replace(/\.html$/, '/')}`;

// url path -> set of element ids on that page
const known = new Map();
for (const rel of pages) {
    const html = readFileSync(path.join(DIST, rel), 'utf8');
    const ids = new Set();
    for (const m of html.matchAll(/\sid="([^"]+)"/g)) ids.add(decodeURIComponent(m[1]));
    known.set(urlOf(rel), ids);
}

let broken = 0;
let checked = 0;

for (const rel of pages) {
    const html = readFileSync(path.join(DIST, rel), 'utf8');
    const from = urlOf(rel);

    // Only the rendered markdown body — site chrome links are generated by Starlight.
    const body = html.split('<div class="sl-markdown-content">')[1] ?? '';

    for (const m of body.matchAll(/href="([^"]+)"/g)) {
        const href = decodeURIComponent(m[1]);
        if (!href.startsWith(`${BASE}/`)) continue;
        // Build assets (expressive-code stylesheets) are not navigable pages.
        if (href.startsWith(`${BASE}/_astro/`)) continue;

        checked += 1;
        const [urlPath, anchor] = href.split('#');
        const target = urlPath.endsWith('/') ? urlPath : `${urlPath}/`;

        if (!known.has(target)) {
            console.error(`БИТАЯ СТРАНИЦА  ${from}  ->  ${href}`);
            broken += 1;
        } else if (anchor && !known.get(target).has(anchor)) {
            console.error(`БИТЫЙ ЯКОРЬ     ${from}  ->  ${href}`);
            broken += 1;
        }
    }
}

console.log(`Проверено ${checked} внутренних ссылок на ${pages.length} страницах, битых: ${broken}`);
process.exit(broken > 0 ? 1 : 0);
